[package]
name = "reversi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
rand = "0.7.3"
indexmap = "1.5.0"
ansi_term = "0.12.1"
libmath = "0.2.1"
rayon = "1.7.0"